const {JSDOM}=require('jsdom');
const fs=require('fs'),assert=require('node:assert/strict');
const code=fs.readFileSync(process.argv[2]||'src/brio.js','utf8');
async function run({own=true,failHead=false,mode=null}={}){
 const dom=new JSDOM('<button id="loggedInLocker" class="b18"><p>Locker</p></button><button id="loggedInShop" class="b18"><p>Shop</p></button><button id="ready">Play</button><input id="nameBox" maxlength="30" value="tester"><canvas id="game"></canvas>',{url:'https://buildroyale.io',runScripts:'outside-only'});
 const w=dom.window;let clock=0,next=0;const timers=new Map,ctxCalls=[];
 const tick=async(ms)=>{const end=clock+ms;for(let i=0;i<500;i++){const due=[...timers].filter(([id,t])=>t.at<=end).sort((a,b)=>a[1].at-b[1].at)[0];if(!due)break;clock=due[1].at;timers.delete(due[0]);if(due[1].period)timers.set(due[0],{...due[1],at:clock+due[1].period});due[1].fn();await flush()}clock=end;await flush()};
 const flush=async()=>{for(let i=0;i<20;i++)await Promise.resolve()};
 w.setTimeout=(fn,ms=0)=>{timers.set(++next,{fn,at:clock+ms});return next};w.clearTimeout=id=>timers.delete(id);w.setInterval=(fn,ms)=>{timers.set(++next,{fn,at:clock+ms,period:ms});return next};w.clearInterval=w.clearTimeout;
 Object.defineProperty(w.performance,'now',{value:()=>clock});w.performance.getEntriesByType=()=>[];
 const ctx={canvas:w.document.querySelector('canvas'),getTransform:()=>({a:1,b:0,c:0,d:1,e:500,f:400}),measureText:t=>({width:t.length*5}),save(){},restore(){},beginPath(){},closePath(){},clip(){},translate(){},drawImage(){},stroke(){},fill(){},arc(){},rect(...a){ctxCalls.push(['rect',...a])},strokeText(...a){ctxCalls.push(['stroke',this.strokeStyle,this.lineWidth,...a])},fillText(...a){ctxCalls.push(['fill',this.fillStyle,...a])}};
 w.HTMLCanvasElement.prototype.getContext=()=>ctx;w.HTMLCanvasElement.prototype.toDataURL=()=> 'data:image/png;base64,blank';Object.assign(ctx.canvas,{width:1000,height:800});ctx.canvas.getBoundingClientRect=()=>({left:0,top:0,width:1000,height:800});
 const srcDesc=Object.getOwnPropertyDescriptor(w.HTMLImageElement.prototype,'src');
 Object.defineProperty(w.HTMLImageElement.prototype,'src',{configurable:true,get(){return this._src||''},set(v){this._src=v;Object.defineProperties(this,{naturalWidth:{configurable:true,value:300},naturalHeight:{configurable:true,value:300}});this.width=this.height=300;w.queueMicrotask(()=>{if(failHead&&String(v).includes('/head/'))this.onerror?.();else this.onload?.()})}});
 w.fetch=async()=>({ok:true,text:async()=>''});w.AbortController=global.AbortController;
 w.indexedDB={open(){const r={result:{objectStoreNames:{contains:()=>true},transaction:()=>({objectStore:()=>({getAll(){const rr={result:mode==='custom'?['body','head','pickaxe'].map(category=>({key:category+':custom1',category,id:'custom1',n:1,name:'custom1',data:'data:image/png;base64,'+category})):[]};w.queueMicrotask(()=>rr.onsuccess?.());return rr}})}),close(){}}};w.queueMicrotask(()=>r.onsuccess?.());return r}};
 w.navigator.clipboard={writeText:async text=>{w.copied=text}};
 const ex={transparentRoofs:true,healthBars:true,numericHealthShield:true,nearestPlayer:true,nearestChest:true,nearestAirdrop:true,permanentMeteor:true,lowHealthWarning:true,lowMatsWarning:true,identifyBots:true,inventorySlots:true,inventoryMaterials:true,inventoryAmmo:true};w.localStorage.setItem('brio_extras_state',JSON.stringify(ex));
 const visuals={body:{mode:'item',id:'shootem'},head:{mode:'item',id:'shootem'},pickaxe:{mode:'item',id:'trophy'},wrap:{mode:'item',id:'sunray'},trail:{mode:'item',id:'trail91'},glider:{mode:'item',id:'glider'},emotes:[0,1,2,3].map(i=>({mode:'item',id:'emote'+(90+i)}))};if(mode){for(const k of ['body','head','pickaxe','trail','wrap','glider'])visuals[k]={mode:mode==='invisible'&&k==='wrap'?'native':mode};visuals.emotes=Array.from({length:4},()=>({mode:mode==='invisible'?'native':mode}));if(mode==='custom'){for(const k of ['body','head','pickaxe'])visuals[k]={mode:'custom',id:'custom1'};for(const k of ['trail','wrap','glider'])visuals[k]={mode:'native'};visuals.emotes=Array.from({length:4},()=>({mode:'native'}))}if(mode==='random')w['Åèa']={shootem:{type:'skin',name:'Shootem'},trophy:{type:'pickaxe',name:'Trophy'},trail91:{type:'trail',name:'Trail'},sunray:{type:'wrap',name:'Sunray'},glider:{type:'glider',name:'Glider'},emote90:{type:'emote',name:'Emote'}}}
 w.localStorage.setItem('br_local_visuals',JSON.stringify(visuals));w.localStorage.setItem('locker2',JSON.stringify({emotes:['emote10','emote11','emote12','emote13']}));
 // Use the page realm for native arrays: global discovery must intercept them.
 const arr=()=>new w.Array;
 const methods={add(x){this['âè'].push(x);x.parent=this;return x},remove(x){const i=this['âè'].indexOf(x);if(i>=0)this['âè'].splice(i,1);x.parent=null},'âá'(x){this['ÉE'].unshift(x);x.parent=this;return x},'Åæê'(x){return this.add(x)}};
 function container(){const o=own?{}:Object.create(methods);Object.assign(o,{'âè':arr(),'ÉE':arr(),'ë':{É:0,Ä:0},opacity:1,visible:true,size:1,A:0,type:'container'});if(own)Object.assign(o,methods);return o}
 function wrapper(src){const im=new w.Image;im.src=src;im['ÀA']=1;return{src,'ÁÄ':im}}
 function drawable(src){return Object.assign(container(),{'À':wrapper(src)})}
 const stage=container();w.testNativeStage=stage;const roof=drawable('/buildart/barnroof.png');stage.add(roof);const nativeRoof=roof['À']['ÁÄ'];
 const player=(id,name,x)=>{const r={id,type:'player','Ée':name,'â':container(),Eâ:container(),'Ëå':drawable('/native-body.png'),head:drawable('/native-head.png'),'ÉãÂ':wrapper('/native-pickaxe.png'),'ä':drawable('/native-pickaxe.png'),'ÄÊâ':drawable('/cosmetics/emotes/emote10.png'),'ÂÅ':drawable('/native-glider.png'),'äÀÊ':wrapper('/native-glider.png'),'Åé':[{type:'pickaxe'},{type:'gun'}],'ÈÆ':0,'åÈ':25,'Â$':40,'ÊÃÄ':[0,0,0,0],'åæ':[3,4,5,6,7],'Ëé':'trail0-','åëÅ':3,'ÆÃÅ':'nativewrap'};r['â']['ë']={É:x,Ä:0};r['â'].add(r.Eâ);stage.add(r['â']);for(const k of['æÄ','AÃå']){r[k]=container();r[k].width=60;r[k].height=10}for(const k of['áË','ÄÂ','ÄãÀ','èÅ'])r[k]=container();return r};
 w.eval(code);await flush();assert(w.document.querySelector('.brioTerm'));w.document.querySelector('#ready').click();const players=arr(),local=player(1,w.document.querySelector('#nameBox').value,0),remote=player(2,'other',1000);players.push(local);players.push(remote);await flush();await tick(1300);
 const S=w.__brio_unlocker_v42;assert(S?.renderer===local);assert(S.meteorObservers.size>0);assert.equal(S.roofSaved.size,1);assert.notEqual(roof['À']['ÁÄ'],nativeRoof);
 if(mode==='native'||mode==='invisible'||mode==='custom'){if(mode==='native'){assert.equal(local['Ëå']['À'].src,'/native-body.png');assert.equal(local['ÉãÂ'].src,'/native-pickaxe.png');assert.equal(local['ÆÃÅ'],'nativewrap');assert.equal(local['Ëé'],'trail0-');assert.equal(local['ÄÊâ']['À'].src,'/cosmetics/emotes/emote10.png')}else if(mode==='custom'){assert.equal(local['Ëå']['À'].src,'data:image/png;base64,body');assert.equal(local.head['À'].src,'data:image/png;base64,head');assert.equal(local['ÉãÂ'].src,'data:image/png;base64,pickaxe')}else{assert(local['Ëå']['À'].src.startsWith('data:image/'));assert(local.head['À'].src.startsWith('data:image/'));assert(local['ÉãÂ'].src.startsWith('data:image/'));local['áË'].opacity=1;assert.equal(local['áË'].opacity,0);local['åëÅ']=9;assert(Number.isNaN(local['åëÅ']));assert(local['äÀÊ'].src.startsWith('data:image/'))}S.destroy();await tick(4000);assert.equal(local['Ëå']['À'].src,'/native-body.png');assert.equal(local['áË'].opacity,1);assert.deepEqual([...S.errors],[]);dom.window.close();return{mode,result:'passed'}}
 const originalBody=wrapper('/body-update.png');local['Ëå']['À']=originalBody;assert.equal(local['Ëå']['À'].src,'/cosmetics/body/shootem.png');assert.equal(local['head']['À'].src,failHead?'/native-head.png':'/cosmetics/head/shootem.png');assert.equal(local['ÉãÂ'].src,'/cosmetics/pickaxe/trophy.png');local['ä']['À']=wrapper('/gun.png');local['ÈÆ']=1;assert.equal(local['ä']['À'].src,'/gun.png');local['ÈÆ']=0;assert.equal(local['ä']['À'].src,'/cosmetics/pickaxe/trophy.png');local['åëÅ']=10;assert.equal(local['Ëé'],'trail91-');assert.equal(local['ÆÃÅ'],'sunray');local['äÀÊ']=wrapper('/reset-glider.png');assert.equal(local['äÀÊ'].src,'/cosmetics/glider/glider.png');
 for(let i=0;i<4;i++){local['ÄÊâ']['À']=wrapper('/cosmetics/emotes/emote'+(10+i)+'.png');assert.equal(local['ÄÊâ']['À'].src,'/cosmetics/emotes/emote'+(mode==='random'?90:90+i)+'.png');const im=new w.Image;im.src='/buildart/emote'+i+'.png';assert.equal(im.src,'/cosmetics/emotes/emote'+(mode==='random'?90:90+i)+'.png')}
 // Delayed parent availability must remain retryable, followed by native retention/restoration.
 const marker={icon:drawable('/buildart/ping-meteor-icon.png'),opacity:1,'ë':{É:500,Ä:20},'èÆÂ':999999,'ÊÈA'(){this.destroyed=true}};players.push(marker);await flush();assert(!marker.parent);stage.add(marker);await flush();assert(S.log.some(x=>x.includes('METEOR NATIVE HOLD INSTALLED')));stage.remove(marker);assert(stage['âè'].includes(marker));marker.opacity=0;assert.equal(marker.opacity,1);marker['ÊÈA']();assert(!marker.destroyed);
 for(const k of['æÄ','AÃå']){const n=remote[k]['âè'].find(n=>n.type==='brioFeature');assert(n);n.Eââ(ctx);assert(ctxCalls.some(c=>c[0]==='stroke'&&c[1]==='#000'&&c[2]===2));assert(ctxCalls.some(c=>c[0]==='fill'&&c[1]==='#fff'));n.Eââ(ctx,2);assert(ctxCalls.some(c=>c[0]==='rect'&&c[3]===29&&c[4]===4));const count=ctxCalls.length;remote[k].width=0;n.Eââ(ctx);assert.equal(ctxCalls.length,count);remote[k].width=60}
 const chest={id:3,type:'chest','â':container()},drop={id:4,type:'object','Àâ':'airdrop','â':container()};chest['â']['ë']={É:2500,Ä:2000};drop['â']['ë']={É:-3000,Ä:1000};players.push(chest,drop);S.localTrack.node.Eââ(ctx);await tick(500);assert.equal(S.chestUi.style.display,'block');assert.equal(S.airdropUi.style.display,'block');assert.equal(S.chestUi.querySelector('.shape').style.background,'rgb(255, 210, 28)');assert.equal(S.airdropUi.querySelector('.shape').style.background,'rgb(242, 139, 22)');
 // Local transform -> all arrow quadrants. Net label angle stays within +/-90 degrees.
 for(let deg=-180;deg<=180;deg+=15){remote['â']['ë']={É:5000*Math.cos(deg*Math.PI/180),Ä:5000*Math.sin(deg*Math.PI/180)};S.localTrack.node.Eââ(ctx);await tick(250);const u=S.nearestUi;assert.equal(u.style.display,'block');const a=+u.style.transform.match(/rotate\(([-.\d]+)deg\)/)[1],flip=u.querySelector('.d').style.transform.includes('180')?180:0,net=((a+flip+540)%360)-180;assert(Math.abs(net)<=90.001);assert.match(u.querySelector('.d').textContent,/m$/);assert.match(u.querySelector('.d').getAttribute('style'),/text-stroke/)}
 remote['â']['ë']={É:10,Ä:0};S.localTrack.node.Eââ(ctx);await tick(250);assert.equal(S.nearestUi.style.display,'none');players.splice(players.indexOf(remote),1);await tick(1000);assert.equal(S.nearestUi.style.display,'none');
 w.document.querySelector('[data-a="phase"]').click();assert.equal(S.botPhase,'match');w.document.querySelector('[data-a="copy"]').click();await flush();assert.match(w.copied,/BRIO 42/);
 S.destroy();await tick(4000);assert(!w.__brio_unlocker_v42);assert.equal(local['Ëå']['À'],originalBody);assert.equal(roof['À']['ÁÄ'],nativeRoof);assert.equal(marker.opacity,0);stage.remove(marker);assert(!stage['âè'].includes(marker));assert.equal(w.document.querySelector('#loggedInLocker').textContent,'Locker');assert.equal(w.localStorage.getItem('br_local_visuals'),JSON.stringify(visuals));
 w.eval(code);await flush();assert(w.__brio_unlocker_v42);w.__brio_unlocker_v42.destroy();assert.deepEqual([...S.errors],[]);dom.window.close();
 return{own,failHead,result:'passed'};
}
(async()=>{for(const opts of[{own:true},{own:false},{own:true,failHead:true},{mode:'native'},{mode:'invisible'},{mode:'random'},{mode:'custom'}])console.log(await run(opts))})().catch(e=>{console.error(e);process.exitCode=1});
