const {JSDOM}=require('jsdom');
const fs=require('fs'),assert=require('node:assert/strict');
const code=fs.readFileSync(process.argv[2]||'src/brio.js','utf8');
async function run({own=true,failHead=false,mode=null,nativeHud=false,detachedHud=false,plainHud=false,emptyHud=false,particleHud=false,saturatedDiscovery=false,decoderProbe=false,engineProbe=false,nearestName=false,hudRebuild=false,stackHud=false,ammoDecoration=false,fullEngine=false,sixSlotHud=false,matchLifecycle=false,probeBudget=false,slotRebuild=false,monochrome=false,inventoryGeometry=false,thresholds=false,corrupt=false,slotCounts=false,selectedSlotLive=false,lootEffects=false}={}){
 const dom=new JSDOM('<button id="loggedInLocker" class="b18"><p>Locker</p></button><button id="loggedInShop" class="b18"><p>Shop</p></button><button id="ready">Play</button><input id="nameBox" maxlength="30" value="tester"><canvas id="game"></canvas>',{url:'https://buildroyale.io',runScripts:'outside-only'});
 const w=dom.window;let clock=0,next=0;const timers=new Map,ctxCalls=[];
 const tick=async(ms)=>{const end=clock+ms;for(let i=0;i<20000;i++){const due=[...timers].filter(([id,t])=>t.at<=end).sort((a,b)=>a[1].at-b[1].at)[0];if(!due)break;clock=due[1].at;timers.delete(due[0]);if(due[1].period)timers.set(due[0],{...due[1],at:clock+due[1].period});due[1].fn();await flush()}clock=end;await flush()};
 const flush=async()=>{for(let i=0;i<20;i++)await Promise.resolve()};
 w.setTimeout=(fn,ms=0)=>{timers.set(++next,{fn,at:clock+ms});return next};w.clearTimeout=id=>timers.delete(id);w.setInterval=(fn,ms)=>{timers.set(++next,{fn,at:clock+ms,period:ms});return next};w.clearInterval=w.clearTimeout;
 Object.defineProperty(w.performance,'now',{value:()=>clock});w.performance.getEntriesByType=()=>[];
 const ctx={canvas:w.document.querySelector('canvas'),getTransform:()=>({a:1,b:0,c:0,d:1,e:500,f:400}),measureText:t=>({width:t.length*5}),save(){},restore(){},beginPath(){},closePath(){},clip(){},translate(){},rotate(a){ctxCalls.push(["rotation",a])},moveTo(){},lineTo(){},scale(...a){ctxCalls.push(["scale",...a])},fillRect(){},strokeRect(...a){ctxCalls.push(['warningRect',...a])},drawImage(){},stroke(){ctxCalls.push(['strokePath',this.strokeStyle,this.lineWidth])},fill(){},arc(){},rect(...a){ctxCalls.push(['rect',...a])},strokeText(...a){ctxCalls.push(['stroke',this.strokeStyle,this.lineWidth,...a])},fillText(...a){ctxCalls.push(['fill',this.fillStyle,...a])}};
 w.HTMLCanvasElement.prototype.getContext=()=>ctx;w.HTMLCanvasElement.prototype.toDataURL=()=> 'data:image/png;base64,blank';Object.assign(ctx.canvas,{width:1000,height:800});ctx.canvas.getBoundingClientRect=()=>({left:0,top:0,width:1000,height:800});
 const srcDesc=Object.getOwnPropertyDescriptor(w.HTMLImageElement.prototype,'src');
 Object.defineProperty(w.HTMLImageElement.prototype,'src',{configurable:true,get(){return this._src||''},set(v){this._src=v;Object.defineProperties(this,{naturalWidth:{configurable:true,value:300},naturalHeight:{configurable:true,value:300}});this.width=this.height=300;w.queueMicrotask(()=>{if(failHead&&String(v).includes('/head/'))this.onerror?.();else this.onload?.()})}});
 const engineFixture=fullEngine?fs.readFileSync('docs/game-sources/engine.js','utf8'):null;
 w.fetch=async()=>({ok:true,text:async()=> engineFixture || 'const assets={"heavy sniper":"buildart/heavy-sniper-native.png","inventoryammo0":"buildart/ammo0.png"};const äèä={"heavy sniper":2,"scar":1,"smg":0,"rpg":4,"shotgun":3,"bolt":2};const Éæ={};Éæ.AÀ="isPreview";Éæ.Åé="weaponSlots";Éæ.äã="rarity";Å.ÃEÅ("player",function(á,å){á.AÀ=å.AÀ;},function(á){},function(á,å){á.Åé=å.Åé;},function(á){});'});w.AbortController=global.AbortController;
 w.indexedDB={open(){const r={result:{objectStoreNames:{contains:()=>true},transaction:()=>({objectStore:()=>({getAll(){const rr={result:mode==='custom'?['body','head','pickaxe'].map(category=>({key:category+':custom1',category,id:'custom1',n:1,name:'custom1',data:'data:image/png;base64,'+category})):[]};w.queueMicrotask(()=>rr.onsuccess?.());return rr}})}),close(){}}};w.queueMicrotask(()=>r.onsuccess?.());return r}};
 w.navigator.clipboard={writeText:async text=>{w.copied=text}};
 let originalDecode, originalCreate;
 if(decoderProbe){originalDecode=function(value){if(value==='throw')throw Error('native decode error');return value};w.msgpack={};Object.defineProperty(w.msgpack,'decode',{value:originalDecode,writable:true,configurable:true,enumerable:false})}
 if(engineProbe){originalCreate=function(a,p){a.testCreated=p.flag;return 73};w.testEngine={'áÉâ':{x(){}},'ÁÂ':{player:{'èæå':originalCreate,'ëåä':function(a,p){return p},remove(){return true}},chest:{'èæå':function(a,p){return p},'ëåä':function(a,p){return p},remove(){return true}}}}}
 if(monochrome)ctx.canvas.style.filter='contrast(1.2)';
 const legacyThresholds={health:30,ammo:[19,19,19,19,19,19],materials:[29,29,29,0]};const ex={lootInvisible:lootEffects,lootMaskTier:lootEffects?'rarity':'item',cleanLoot:lootEffects,...(!thresholds?{warningThresholds:legacyThresholds}:corrupt?{warningThresholds:{health:null,ammo:[-1,'',null,2.5,1e20,7],materials:[0,NaN,{},4]}}:{}),monochrome,buildMaterialLabels:true,deployableLabels:true,deployableRadius:true,highlightLoot:true,noFoliage:true,nearestPlayerName:nearestName,transparentRoofs:true,healthBars:true,numericHealthShield:true,nearestPlayer:true,nearestChest:true,nearestAirdrop:true,permanentMeteor:true,lowHealthWarning:true,lowMatsWarning:true,lowAmmoWarning:true,identifyBots:true,inventorySlots:true,inventoryMaterials:true,inventoryAmmo:true};w.localStorage.setItem('brio_extras_state',JSON.stringify(ex));
 const visuals={body:{mode:'item',id:'shootem'},head:{mode:'item',id:'shootem'},pickaxe:{mode:'item',id:'trophy'},wrap:{mode:'item',id:'sunray'},trail:{mode:'item',id:'trail91'},glider:{mode:'item',id:'glider'},emotes:[0,1,2,3].map(i=>({mode:'item',id:'emote'+(90+i)}))};if(mode){for(const k of ['body','head','pickaxe','trail','wrap','glider'])visuals[k]={mode:mode==='invisible'&&k==='wrap'?'native':mode};visuals.emotes=Array.from({length:4},()=>({mode:mode==='invisible'?'native':mode}));if(mode==='custom'){for(const k of ['body','head','pickaxe'])visuals[k]={mode:'custom',id:'custom1'};for(const k of ['trail','wrap','glider'])visuals[k]={mode:'native'};visuals.emotes=Array.from({length:4},()=>({mode:'native'}))}if(mode==='random')w['Åèa']={shootem:{type:'skin',name:'Shootem'},trophy:{type:'pickaxe',name:'Trophy'},trail91:{type:'trail',name:'Trail'},sunray:{type:'wrap',name:'Sunray'},glider:{type:'glider',name:'Glider'},emote90:{type:'emote',name:'Emote'}}}
 w.localStorage.setItem('br_local_visuals',JSON.stringify(visuals));w.localStorage.setItem('locker2',JSON.stringify({emotes:['emote10','emote11','emote12','emote13']}));
 // Use the page realm for native arrays: global discovery must intercept them.
 const arr=()=>new w.Array;
 const methods={add(x){this['âè'].push(x);x.parent=this;return x},remove(x){const i=this['âè'].indexOf(x);if(i>=0)this['âè'].splice(i,1);x.parent=null},'âá'(x){this['ÉE'].unshift(x);x.parent=this;return x},'Åæê'(x){return this.add(x)}};
 function container(){const o=own?{}:Object.create(methods);Object.assign(o,{'âè':arr(),'ÉE':arr(),'ë':{É:0,Ä:0},opacity:1,visible:true,size:1,A:0,type:'container'});if(own)Object.assign(o,methods);return o}
 function wrapper(src){const im=new w.Image;im.src=src;im['ÀA']=1;return{src,'ÁÄ':im}}
 function drawable(src){return Object.assign(container(),{'À':wrapper(src)})}
 let hiddenHud; const hiddenMap=Object.assign(container(),{éa(){}});const mapRoot=container();mapRoot.add(hiddenMap);const stage=container();w.testNativeStage=stage;w.hostileScene=new Proxy({}, {get(){throw Error('native getter rejected')}});const roof=drawable('/buildart/barnroof.png');stage.add(roof);const nativeRoof=roof['À']['ÁÄ'];
 if(nativeHud){class NativeGroup{constructor(){Object.assign(this,container());this.type='nativeContainer'}éa(ctx,s,alpha=1){ctx.save();ctx.translate(this['ë'].É/s,this['ë'].Ä/s);this['âè'].forEach(n=>n.éa?.(ctx,s,alpha));ctx.restore()}Eââ(ctx,s){this.éa(ctx,s,1)}}class NativeSprite extends NativeGroup{constructor(res,x=0,y=0,width=40,height=40,opacity=1){super();Object.assign(this,{'À':res,'ë':{É:x,Ä:y},width,height,opacity,type:'image'})}éa(ctx,s){ctx.drawImage(this['À']['ÁÄ'],this['ë'].É/s,this['ë'].Ä/s,this.width/s,this.height/s)}}class NativeText extends NativeGroup{constructor(text,x=0,y=0,color='#fff',font='Arial',size=14,weight='bold',opacity=1,align='center'){super();Object.assign(this,{text,'ë':{É:x,Ä:y},fillStyle:color,fontFamily:font,fontSize:size,fontWeight:weight,opacity,textAlign:align,type:'text',width:String(text).length*10,height:14})}éa(ctx,s){ctx.fillStyle=this.fillStyle;ctx.font=this.fontWeight+' '+this.fontSize/s+'px '+this.fontFamily;ctx.fillText(this.text,this['ë'].É/s,this['ë'].Ä/s)}}const hud=new NativeGroup;hiddenHud=hud;if(!detachedHud)stage.add(hud);for(let i=0;i<5;i++){const unit=new NativeGroup;unit['ë'].É=i*70;hud.add(unit);unit.add(new NativeSprite(wrapper('/buildart/inv'+i+'.png')));if(!emptyHud)unit.add(new NativeSprite(wrapper('/buildart/scar.png'),0,0,32,32));if(ammoDecoration)unit.add(new NativeSprite(wrapper('/buildart/ammo1.png'),12,-12,8,8));unit.add(new NativeText(String(i+1),-15,15,'#eee','Chewy',12))}for(const [i,name]of ['wood','brick','metal','scrap'].entries()){const unit=new NativeGroup;unit['ë']={É:i*70,Ä:80};hud.add(unit);unit.add(new NativeSprite(wrapper('/buildart/'+name+'.png'),-15,0,30,30));unit.add(new NativeText(String([60,10,10,2][i]),20,0,'#fff','Chewy',14))}for(let i=0;i<5;i++){const unit=new NativeGroup;unit['ë']={É:i*70,Ä:130};hud.add(unit);unit.add(new NativeSprite(wrapper('/buildart/'+(stackHud?'stack':'ammo')+i+'.png'),-15,0,30,30));unit.add(new NativeText('0',20,0,'#fff','Chewy',14))}
 if(sixSlotHud){for(const old of [...hud['âè'].slice(0,5)])hud.remove(old);for(let i=0;i<6;i++){const holder=new NativeGroup;holder['ë']={É:-650+i*110,Ä:-100};hud.add(holder);const unit=i===4?new NativeGroup:new NativeSprite(wrapper('/buildart/inv'+(i%6)+'.png'),0,i===1?-10:0,100,100);if(i===4)Object.assign(unit,{width:100,height:100,type:'rectangle'});holder.add(unit);unit.add(new NativeText(String(i+1),0,75,'#fff','Arial Black',23));if(slotCounts&&i>0){unit.add(new NativeText('98765',-35,35,'#000','Arial Black',23,'',1,'left'));unit.add(new NativeText('98765',-35,35,'#fff','Arial Black',23,'',1,'left'));}if(i!==4){unit.add(new NativeSprite(wrapper(i===0?'/native-pickaxe.png':'/buildart/scar.png'),0,0,104,104));if(i!==0)unit.add(new NativeSprite(wrapper('/buildart/ammo1.png'),25,-25,30,30));}}}
 }
 if(plainHud){const walk=n=>{for(const c of n['âè']||[])walk(c);for(const key of ['éa','Eââ'])if(typeof n[key]==='function')Object.defineProperty(n,key,{value:n[key],writable:true,configurable:true,enumerable:true});Object.setPrototypeOf(n,Object.prototype)};walk(hiddenHud)}
 const player=(id,name,x)=>{const r={id,type:'player','Ée':name,'â':container(),Eâ:container(),'Ëå':drawable('/native-body.png'),head:drawable('/native-head.png'),'ÉãÂ':wrapper('/native-pickaxe.png'),'ä':drawable('/native-pickaxe.png'),'ÄÊâ':drawable('/cosmetics/emotes/emote10.png'),'ÂÅ':drawable('/native-glider.png'),'äÀÊ':wrapper('/native-glider.png'),'Åé':[{type:'pickaxe'},{type:'gun'}],'ÈÆ':0,'åÈ':25,'Â$':40,'ÊÃÄ':[0,0,0,0],'åæ':[3,4,5,6,7],'Ëé':'trail0-','åëÅ':3,'ÆÃÅ':'nativewrap'};r['â']['ë']={É:x,Ä:0};r['â'].add(r.Eâ);stage.add(r['â']);for(const k of['æÄ','AÃå']){r[k]=container();r[k].width=60;r[k].height=k==='AÃå'?4:10}for(const k of['áË','ÄÂ','ÄãÀ','èÅ'])r[k]=container();return r};
 const nativeForEach=w.Array.prototype.forEach;w.eval(code);await flush();assert.equal(w.document.querySelector('.brioTerm .head b').textContent,'BRIO v52');
 const extras=Array.from(w.document.querySelectorAll('.brioModal')).find(e=>e.querySelector('header b')?.textContent==='BRIO Extras');assert(extras);
 const tab=label=>Array.from(extras.querySelectorAll('.brioTabs button')).find(b=>b.textContent===label).click();
 tab('Challenges');assert(!extras.textContent.includes('Foliage invisible'));
 const monoInput=Array.from(extras.querySelectorAll('.brioOpt')).find(r=>r.textContent.includes('Monochrome vision')).querySelector('input');
 tab('Modifiers');assert.equal(Array.from(extras.querySelectorAll('.brioOpt span')).filter(e=>e.textContent.includes('TEST PROFILE')).length,16);
 for(const name of ['Inventory: ammo by type','Permanent meteor location','Health/shield numbers','Player name in nearest arrow']){const row=Array.from(extras.querySelectorAll('.brioOpt')).find(r=>r.textContent.includes(name));assert(row.textContent.includes('PROVEN'));assert(!row.textContent.includes('TEST PROFILE'));}
 for(const name of ['Build material labels','Deployable labels','Deployable effect-radius','Highlight loot'])assert(!extras.textContent.includes(name));
 const contrast=Array.from(extras.querySelectorAll('.brioOpt')).find(r=>r.textContent.includes('High-contrast players'));assert(contrast);assert(!contrast.textContent.includes('TEST PROFILE'));
 for(const key of ['buildMaterialLabels','deployableLabels','deployableRadius','highlightLoot','noFoliage'])assert(!Object.hasOwn(JSON.parse(w.localStorage.getItem('brio_extras_state')),key));
w.document.querySelector('#ready').click();if(monochrome){assert(w.document.documentElement.hasAttribute('data-brio-mono-page'));assert.equal(ctx.canvas.style.filter,'contrast(1.2) grayscale(1)');const newCanvas=w.document.createElement('canvas');w.document.body.appendChild(newCanvas);assert.equal(w.getComputedStyle(newCanvas).filter,'grayscale(1)');assert(!newCanvas.hasAttribute('data-brio-mono'));monoInput.checked=false;monoInput.dispatchEvent(new w.Event('change'));assert(!w.document.documentElement.hasAttribute('data-brio-mono-page'));assert.equal(ctx.canvas.style.filter,'contrast(1.2)');monoInput.checked=true;monoInput.dispatchEvent(new w.Event('change'));assert.equal(newCanvas.style.filter,'grayscale(1)');assert.equal(ctx.canvas.style.filter,'contrast(1.2) grayscale(1)');}
 const players=arr(),local=player(1,w.document.querySelector('#nameBox').value,0),remote=player(2,'other',1000);players.push(local);players.push(remote);await flush();if(particleHud){const particle=Object.assign(drawable('/buildart/wood.png'),{type:'particle',width:50,height:50,éa(){}});const text=Object.assign(container(),{type:'text',text:'+5',éa(){}});particle.add(text);stage.add(particle);stage['âè'].forEach(()=>{})}if(saturatedDiscovery){for(let i=0;i<160;i++){const n=Object.assign(container(),{éa(){}});const a=arr();a.push(n);a.forEach(()=>{})}}if(detachedHud){hiddenHud.éa(ctx,1);mapRoot['âè'].forEach(n=>n.éa(ctx,1));}await tick(1300);
 const S=w.__brio_unlocker_v52;assert(S?.renderer===local);assert(S.log.some(x=>x.includes('FULL NATIVE SOURCE CHUNK')));assert(S.log.some(x=>x.includes('astParsed')&&x.includes('true')));assert.equal(S.log.filter(x=>x.includes('FULL NATIVE SOURCE CHUNK')).map(x=>JSON.parse(x.slice(x.indexOf('{'))).text).join(''),await (await w.fetch()).text());if(particleHud)assert(!S.log.filter(x=>x.includes('NATIVE HUD WIDGET')).some(x=>x.includes('particle')));const schema=S.log.find(x=>x.includes('DECODED FIELD SCHEMA'));assert(schema?.includes('isPreview'));if(fullEngine){assert.equal(S.ammoTypeMap.get('rifle'),2,JSON.stringify([...S.ammoTypeMap]));assert(S.ammoTypeMap.size>=30)}assert(S.hudAssetPaths.get('heavy sniper')===(fullEngine?'/buildart/heavysniper.png':'/buildart/heavy-sniper-native.png'));assert(S.log.some(x=>x.includes('NATIVE CALLBACK AUDIT')&&x.includes('update')&&x.includes('weaponSlots')));assert(S.meteorObservers.size>0);assert.equal(S.roofSaved.size,1);assert.notEqual(roof['À']['ÁÄ'],nativeRoof);
 if(decoderProbe){assert.notEqual(w.msgpack.decode,originalDecode);const payload=[{t:'x',p:[902,'chest',100,200,0,1],contents:[{type:'scar',rarity:2}],seed:123},{t:'x',p:[903,'player',0,0,0,1],droid:true},{t:'y',a:[902,100,200,0],contents:[{type:'scar'}]}];assert.equal(w.msgpack.decode(payload),payload);assert.equal(payload[0].contents[0].type,'scar');payload[0].contents[0].type='changed-after-return';assert(S.log.some(x=>x.includes('INCOMING TARGET PAYLOAD')&&x.includes('scar')));assert.throws(()=>w.msgpack.decode('throw'),/native decode error/);assert.equal(Object.getOwnPropertyDescriptor(w.msgpack,'decode').enumerable,false)}
 if(probeBudget){
  for(let i=0;i<700;i++)w.msgpack.decode([{t:'x',p:[10000+i,'gun',0,0,0,1],gunType:'scar'}]);
  w.msgpack.decode([{t:'x',p:[700,'player',0,0,0,1],opaque:0}]);
  for(let i=0;i<2500;i++)w.msgpack.decode([{t:'y',a:[700,i,i,i],effects:{},team:[700]}]);
  const early=S.log.filter(l=>l.includes('INCOMING TARGET PAYLOAD')).length;assert(early<12);
  for(let i=0;i<500;i++)w.msgpack.decode([{t:'y',a:[700,0,0,0],['novel'+i]:i}]);
  const before=S.log.filter(l=>l.includes('INCOMING TARGET PAYLOAD')).length;
  const late={t:'x',p:[888,'object',0,0,0,1],type:'airdrop',opaqueSeed:87};assert.equal(w.msgpack.decode([late])[0],late);
  assert(S.log.filter(l=>l.includes('INCOMING TARGET PAYLOAD')).length>before);assert(S.log.some(l=>l.includes('INCOMING TARGET PAYLOAD')&&l.includes('opaqueSeed')));
  const trafficStart=S.log.filter(l=>l.includes('INCOMING TARGET PAYLOAD')).length;
  for(let i=0;i<1000;i++)w.msgpack.decode([{t:'y',a:[888,0,0,0],landProgress:i/1000,health:100-i/10}]);
  assert(S.log.filter(l=>l.includes('INCOMING TARGET PAYLOAD')).length-trafficStart<8);
  w.msgpack.decode([{t:'y',a:[888,0,0,0],opaqueLateContents:['unknown-evidence']}]);assert(S.log.some(l=>l.includes('opaqueLateContents')));

  const env={resources:Array.from({length:1000},(_,i)=>[i,i,i]),resourceNames:['chest','bubbles'],chests:Array.from({length:50},(_,i)=>({id:i,opaque:i}))};
  w.msgpack.decode([{t:'e',envs:env}]);const chunks=S.log.filter(l=>l.includes('ENVIRONMENT TARGET CHUNK')).map(l=>JSON.parse(l.slice(l.indexOf('{'))).data).filter(d=>d.key==='chests');assert.deepEqual(Array.from(chunks.flatMap(d=>d.entries),d=>d.id),Array.from({length:50},(_,i)=>i));
  w.msgpack.decode([{t:'circle',state:'waiting'}]);assert.equal(S.botPhase,'match');
  const withGetter={t:'y',a:[700,0,0,0]};Object.defineProperty(withGetter,'unsafe',{enumerable:true,get(){throw Error('must not invoke accessor')}});w.msgpack.decode([withGetter]);
 }
 if(engineProbe){const target={},payload={flag:true,opaqueSeed:17};assert.equal(w.testEngine['ÁÂ'].player['èæå'](target,payload),73);assert.equal(target.testCreated,true);assert.equal(payload.opaqueSeed,17);assert(S.log.some(x=>x.includes('NATIVE CALLBACK PAYLOAD')&&x.includes('opaqueSeed')))}
 if(mode==='native'||mode==='invisible'||mode==='custom'){if(mode==='native'){assert.equal(local['Ëå']['À'].src,'/native-body.png');assert.equal(local['ÉãÂ'].src,'/native-pickaxe.png');assert.equal(local['ÆÃÅ'],'nativewrap');assert.equal(local['Ëé'],'trail0-');assert.equal(local['ÄÊâ']['À'].src,'/cosmetics/emotes/emote10.png')}else if(mode==='custom'){assert.equal(local['Ëå']['À'].src,'data:image/png;base64,body');assert.equal(local.head['À'].src,'data:image/png;base64,head');assert.equal(local['ÉãÂ'].src,'data:image/png;base64,pickaxe')}else{assert(local['Ëå']['À'].src.startsWith('data:image/'));assert(local.head['À'].src.startsWith('data:image/'));assert(local['ÉãÂ'].src.startsWith('data:image/'));local['áË'].opacity=1;assert.equal(local['áË'].opacity,0);local['åëÅ']=9;assert(Number.isNaN(local['åëÅ']));assert(local['äÀÊ'].src.startsWith('data:image/'))}S.destroy();await tick(4000);assert.equal(local['Ëå']['À'].src,'/native-body.png');assert.equal(local['áË'].opacity,1);assert.deepEqual([...S.errors],[]);dom.window.close();return{mode,result:'passed'}}
 // V48 integration: operate actual controls and native attached nodes, no test exports.
 if(thresholds){
  const inputs=Array.from(extras.querySelectorAll('.brioThresholds input')), row=extras.querySelector('.brioThresholds');
  assert.equal(inputs.length,11);assert.equal(extras.querySelectorAll('.brioThresholds').length,3);assert.equal(w.getComputedStyle(row).flexWrap,'nowrap');
  for(const [kind,name]of [['health','Low-health visual warning'],['ammo','Low-ammo visual warning'],['materials','Low-material warning']]){const group=extras.querySelector('[data-warning-kind="'+kind+'"]').closest('.brioThresholds');assert(group.previousElementSibling.textContent.includes(name));}
  const field=(kind,i=0)=>Array.from(extras.querySelectorAll('.brioThresholds input')).find(n=>n.dataset.warningKind===kind&&+n.dataset.warningIndex===i);
  const saved=()=>JSON.parse(w.localStorage.getItem('brio_extras_state')).warningThresholds;
  const edit=(kind,i,value)=>{const n=field(kind,i);n.value=String(value);n.dispatchEvent(new w.Event('input',{bubbles:true}));};
  const expected=corrupt?{health:20,ammo:[30,30,10,15,5,7],materials:[0,30,30,4]}:{health:20,ammo:[30,30,10,15,5,5],materials:[30,30,30,1]};
  assert.deepEqual(saved(),expected);
  for(const [kind,modifier]of [['health','Low-health visual warning'],['ammo','Low-ammo visual warning'],['materials','Low-material warning']]){
   const toggle=Array.from(extras.querySelectorAll('.brioOpt')).find(n=>n.textContent.includes(modifier)).querySelector('input[type=checkbox]');
   toggle.click();assert(field(kind).matches(':disabled'));assert.equal(w.getComputedStyle(field(kind).closest('fieldset')).opacity,'0.4');
   toggle.click();assert(!field(kind).matches(':disabled'));
  }
  // Blank/negative/fractional/out-of-range inputs preserve the last valid saved choice and normalize on blur.
  for(const v of ['','-1','2.5','1000001']){field('ammo',0).value=v;field('ammo',0).dispatchEvent(new w.Event('input'));assert.equal(saved().ammo[0],expected.ammo[0]);field('ammo',0).dispatchEvent(new w.Event('blur'));assert.equal(field('ammo',0).value,String(expected.ammo[0]));}
  // Return to requested defaults even in the corrupt-storage scenario, through UI rather than internal helpers.
  edit('health',0,20);for(const [i,v]of [30,30,10,15,5,5].entries())edit('ammo',i,v);for(const [i,v]of [30,30,30,1].entries())edit('materials',i,v);
  const defaults=saved();assert.deepEqual(defaults,{health:20,ammo:[30,30,10,15,5,5],materials:[30,30,30,1]});
  const healthDraw=r=>{ctxCalls.length=0;for(const n of r.Eâ['âè'])if(n.type==='brioFeature')n.Eââ(ctx,1);return ctxCalls.filter(c=>c[0]==='strokePath'&&c[1]==='#ff2020').length};
  for(const r of [local,remote]){r['åÈ']=19;assert.equal(healthDraw(r),r===local?1:0);r['åÈ']=20;assert.equal(healthDraw(r),r===local?1:0);r['åÈ']=21;assert.equal(healthDraw(r),0);r['åÈ']=undefined;assert.equal(healthDraw(r),0);}
  edit('health',0,45);local['åÈ']=remote['åÈ']=44;assert.equal(healthDraw(local),1);assert.equal(healthDraw(remote),0);edit('health',0,0);assert.equal(healthDraw(local),0);edit('health',0,20);
  const slotDraw=()=>{const got=[];for(const n of S.hudWarnNodes.values()){if(n.__brioHudRecord.kind!=='slots')continue;ctxCalls.length=0;n.Eââ(ctx,1);if(ctxCalls.some(c=>c[0]==='warningRect'))got.push(n.__brioHudRecord.slotIndex)}return got};
  if(nativeHud){
   local['ÊÃÄ']=[30,30,30,1];local['Åé']=[{type:'pickaxe'},...['smg','scar','bolt','shotgun','rpg'].map(type=>({type}))];local['áAæ']=[0,0,0,0,0];
   // Update live fixture emblems just as native inventory rebuilding does when weapon types change.
   for(const rec of S.hudTemplates.slots){const emblem=rec.nodes.find(n=>/\/ammo[0-4]\.png$/.test(n['À']?.src||''));if(emblem)emblem['À']=wrapper('/buildart/ammo'+(rec.slotIndex-1)+'.png');}
   local['åæ']=[29,29,9,14,4];assert.deepEqual(slotDraw(),[1,2,3,4,5]);local['åæ']=[30,30,10,15,5];assert.deepEqual(slotDraw(),[1,2,3,4,5]);local['åæ']=[31,31,11,16,6];assert.deepEqual(slotDraw(),[]);
   for(let i=0;i<5;i++){edit('ammo',i,100+i);local['åæ'][i]=99+i;}assert.deepEqual(slotDraw(),[1,2,3,4,5]);edit('ammo',0,0);assert.deepEqual(slotDraw(),[2,3,4,5]);
   local['Åé'][5]={type:'grappler'};local['áAæ'][4]=0;assert(slotDraw().includes(5));local['áAæ'][4]=5;assert(slotDraw().includes(5));local['áAæ'][4]=6;assert(!slotDraw().includes(5));edit('ammo',5,8);local['áAæ'][4]=7;assert(slotDraw().includes(5));local['ÈÆ']=1;assert(slotDraw().includes(5));local['áAæ'][4]=-1;assert(!slotDraw().includes(5));
   for(const [i,v]of [30,30,10,15,5,5].entries())edit('ammo',i,v);
   const matDraw=()=>{const got=[];for(const n of S.hudWarnNodes.values()){if(n.__brioHudRecord.kind!=='materials')continue;ctxCalls.length=0;n.Eââ(ctx,1);if(ctxCalls.length)got.push(n.__brioHudRecord.path)}return got};
   local['Åé']=[{type:'pickaxe'},{type:'gun'}];local['áAæ']=[];local['ÊÃÄ']=[29,29,29,0];assert.equal(matDraw().length,4);local['ÊÃÄ']=[30,30,30,1];assert.equal(matDraw().length,4);local['ÊÃÄ']=[31,31,31,2];assert.equal(matDraw().length,0);
   for(let i=0;i<4;i++){edit('materials',i,50+i);local['ÊÃÄ'][i]=49+i;}assert.equal(matDraw().length,4);edit('materials',3,0);assert.equal(matDraw().length,3);
   for(const rec of S.hudTemplates.slots){const emblem=rec.nodes.find(n=>/\/ammo[0-4]\.png$/.test(n['À']?.src||''));if(emblem)emblem['À']=wrapper('/buildart/ammo1.png');}
  }
  // Remote default inclusive boundaries, including scraps0 vs1, on captured and fallback paths.
  for(const [i,v]of [30,30,10,15,5,5].entries())edit('ammo',i,v);for(const [i,v]of [30,30,30,1].entries())edit('materials',i,v);
  remote['åæ']=[29,29,9,14,4];remote['ÊÃÄ']=[29,29,29,0];remote['Åé']=[{type:'pickaxe'},{type:'gun'}];
  while(Math.sin(clock/140)<0)await tick(50);ctxCalls.length=0;S.invNodes.get(remote).Eââ(ctx,1);for(const v of ['29','9','14','4','0'])assert(ctxCalls.some(c=>c[0]==='fill'&&c[1]==='#ff2020'&&c[2]===v));
  remote['åæ']=[30,30,10,15,5];remote['ÊÃÄ']=[30,30,30,1];ctxCalls.length=0;S.invNodes.get(remote).Eââ(ctx,1);for(const v of ['30','10','15','5','1'])assert(ctxCalls.some(c=>c[0]==='fill'&&c[1]==='#ff2020'&&c[2]===v));remote['åæ']=[31,31,11,16,6];remote['ÊÃÄ']=[31,31,31,2];ctxCalls.length=0;S.invNodes.get(remote).Eââ(ctx,1);assert(!ctxCalls.some(c=>c[0]==='fill'&&c[1]==='#ff2020'));
  // Remote reserves/materials share the edited settings, native clones and fallback both exercised.
  for(let i=0;i<5;i++)edit('ammo',i,100+i);for(let i=0;i<4;i++)edit('materials',i,50+i);
  remote['åæ']=[99,100,101,102,103];remote['ÊÃÄ']=[49,50,51,52];remote['Åé']=[{type:'pickaxe'},{type:'grappler'},{type:'empty'},{type:'empty'},{type:'empty'},{type:'empty'}];remote['áAæ']=[0,0,0,0,0];edit('ammo',5,1);
  while(Math.sin(clock/140)<0)await tick(50);ctxCalls.length=0;S.invNodes.get(remote).Eââ(ctx,1);
  for(const v of ['99','100','101','102','103','49','50','51','52'])assert(ctxCalls.some(c=>c[0]==='fill'&&c[1]==='#ff2020'&&c[2]===v),v);
  assert.equal(ctxCalls.filter(c=>c[0]==='warningRect').length,1,'remote grappler charge warning on native/fallback slot');
  remote['áAæ'][0]=1;ctxCalls.length=0;S.invNodes.get(remote).Eââ(ctx,1);assert.equal(ctxCalls.filter(c=>c[0]==='warningRect').length,1);remote['áAæ'][0]=2;ctxCalls.length=0;S.invNodes.get(remote).Eââ(ctx,1);assert.equal(ctxCalls.filter(c=>c[0]==='warningRect').length,0);
  for(const [name,kind,values]of [['Low-ammo visual warning','ammo',['99','100','101','102','103']],['Low-material warning','materials',['49','50','51','52']]]){
   const toggle=Array.from(extras.querySelectorAll('.brioOpt')).find(n=>n.textContent.includes(name)).querySelector('input[type=checkbox]');
   toggle.click();ctxCalls.length=0;S.invNodes.get(remote).Eââ(ctx,1);assert(!ctxCalls.some(c=>c[0]==='fill'&&c[1]==='#ff2020'&&values.includes(c[2])));
   if(kind==='ammo')assert.equal(ctxCalls.filter(c=>c[0]==='warningRect').length,0);toggle.click();
  }
  edit('ammo',5,0);remote['áAæ'][0]=0;ctxCalls.length=0;S.invNodes.get(remote).Eââ(ctx,1);assert.equal(ctxCalls.filter(c=>c[0]==='warningRect').length,1,'zero threshold includes known zero charges');remote['Åé'][1]={type:'signal flare'};edit('ammo',5,1000000);ctxCalls.length=0;S.invNodes.get(remote).Eââ(ctx,1);assert.equal(ctxCalls.filter(c=>c[0]==='warningRect').length,0,'flare never receives slot warning');
  if(nativeHud){local['Åé']=[{type:'pickaxe'},{type:'signal flare'},{type:'grappler'}];local['áAæ']=[0,0];edit('ammo',5,0);assert.deepEqual(slotDraw(),[2]);local['áAæ'][1]=1;assert.deepEqual(slotDraw(),[]);local['Åé']=[{type:'pickaxe'},{type:'gun'}];local['áAæ']=[];}
  edit('ammo',5,1);const persisted=saved();tab('Challenges');tab('Modifiers');assert.deepEqual(saved(),persisted);assert.equal(field('ammo',5).value,'1');
  // Common historical checks below use their adjusted legacy thresholds explicitly; they are not the V48 defaults.
  const z=JSON.parse(w.localStorage.getItem('brio_extras_state'));z.warningThresholds=legacyThresholds;w.localStorage.setItem('brio_extras_state',JSON.stringify(z));await tick(600);
  remote['Åé']=[{type:'pickaxe'},{type:'gun'}];remote['áAæ']=[];local['ÊÃÄ']=[60,10,10,2];local['åæ']=[3,4,5,6,7];
 }
 if(hudRebuild){const unit=hiddenHud['âè'].find(n=>n['âè'].some(c=>c['À']?.src==='/buildart/wood.png'));for(let i=0;i<90;i++){const old=unit['âè'].find(n=>n['À']);const replacement=new old.constructor(old['À'],old['ë'].É,old['ë'].Ä,old.width,old.height);unit.remove(old);unit.add(replacement);await tick(300)}assert(S.hudInspectionCount>80);assert.equal(S.hudWarnNodes.size,9)}
 if(nativeHud){assert.deepEqual({...S.hudStatus.counts},{slots:5,materials:4,ammo:5});assert.equal(S.hudWarnNodes.size,9);if(stackHud)assert(S.hudTemplates.ammo.every(r=>r.path.includes('/stack')));local['ÊÃÄ']=[29,30,31,1];local['åæ']=[20,20,20,20,20];await tick(500);const before=ctxCalls.filter(x=>x[0]==='warningRect').length;for(const n of S.hudWarnNodes.values())n.Eââ(ctx,1);assert.equal(ctxCalls.filter(x=>x[0]==='warningRect').length-before,1);remote['ÊÃÄ']=[12,34,56,4];remote['Åé']=[{type:'pickaxe'},{type:'heavy sniper','äã':4},{type:'mini','äã':1},{type:'empty'},{type:'gun','äã':0},{type:'bandages','äã':0}];S.invNodes.get(remote).Eââ(ctx,1);assert([...S.nativeInvClones.get(remote).rows[0].units[0].pairs].some(p=>p.node['À']?.src===(fullEngine?'/buildart/heavysniper.png':'/buildart/heavy-sniper-native.png')));assert(S.nativeInvClones.get(remote).rows.length===3,S.log.filter(x=>x.includes('REPLICA UNAVAILABLE')).join('\n'));await flush();for(const im of S.invAssets.values()){assert.equal(im['ÀA'],1);assert.equal(im['ÁÅe'],im.width/2);assert.equal(im['âÅÉ'],im.height/2)}for(const val of ['12','34','56','4'])assert(ctxCalls.some(x=>x[0]==='fill'&&x[2]===val));assert.equal(S.hudWarnNodes.size,9);local['ÊÃÄ']=[60,10,10,2];local['åæ']=[19,20,21,undefined,0];const ammoBefore=ctxCalls.filter(x=>x[0]==='warningRect').length;local['ÊÃÄ']=[30,30,30,2];for(const n of S.hudWarnNodes.values())n.Eââ(ctx,1);assert.equal(ctxCalls.filter(x=>x[0]==='warningRect').length-ammoBefore,0)}
 if(slotCounts){
  const pairs=S.nativeInvClones.get(remote).rows.find(r=>r.kind==='slots').units.flatMap(u=>u.pairs);
  const counts=pairs.filter(p=>p.source.text==='98765');assert.equal(counts.length,10);
  for(const p of counts){assert.equal(p.source.opacity,1);assert.equal(p.source.text,'98765');assert.equal(p.node.opacity,0);ctxCalls.length=0;p.node.éa(ctx,1);assert.equal(ctxCalls.length,0);}
  assert(pairs.some(p=>p.source.type==='text'&&p.source.textAlign==='center'&&p.node.opacity===0),'remote hotkey caption hidden');
 }

 if(nativeHud){
  local['ÊÃÄ']=[30,30,30,2];local['Åé']=[{type:'pickaxe'},{type:'scar'},{type:'scar'},{type:'mini'},{type:'scar'},{type:'mysterygun'}];local['áAæ']=[3,4,0,5,0];local['åæ']=[0,16,0,0,0];local['ÈÆ']=2;await tick(600);
  const draws=()=>{ctxCalls.length=0;for(const [root,n]of S.hudWarnNodes){const before=ctxCalls.length;n.Eââ(ctx,2);if(ctxCalls.length>before)ctxCalls.push(['slot',n.__brioHudRecord.slotIndex])}return ctxCalls.filter(c=>c[0]==='slot').map(c=>c[1])};
  assert.deepEqual(draws(),[1]); // 19 warns despite being unequipped; 20/21 do not.
  local['ÈÆ']=1;assert.deepEqual(draws(),[1]);local['åæ'][1]=0;assert.deepEqual(draws(),[1,2,4]);
  local['áAæ'][0]=-1;local['áAæ'][1]=undefined;assert.deepEqual(draws(),[4]);
  local['Åé'][4]={type:'bandages'};assert.deepEqual(draws(),[]);local['Åé'][4]={type:'grappler'};assert.deepEqual(draws(),[4]);
  local['Åé'][4]={type:'scar'};local['áAæ'][3]=5;local['åæ'][1]=14;assert.deepEqual(draws(),[4]);
  const rec=S.hudTemplates.slots.find(r=>r.slotIndex===4),node=S.hudWarnNodes.get(rec.holder);node.Eââ(ctx,2);assert(ctxCalls.some(c=>c[0]==='warningRect'&&c[1]===(rec.slotBounds.left-3)/2&&c[3]===(rec.slotBounds.width+6)/2));
  if(inventoryGeometry){ctxCalls.length=0;remote['Åé']=[{type:'pickaxe'},{type:'scar'},{type:'empty'},{type:'scar'},{type:'empty'},{type:'scar'}];S.invNodes.get(remote).Eââ(ctx,1);const scales=ctxCalls.filter(c=>c[0]==='scale'&&Math.abs(c[1]-.262)<1e-9);assert.equal(scales.length,5,'native weapon backgrounds grow proportionally to26.2px');assert(ctxCalls.filter(c=>c[0]==='strokePath'&&c[1]==='#ff2020').every(c=>c[2]===1.2),'empty X uses the V45 display stroke');}
  if(sixSlotHud){assert.equal(rec.root.type,'rectangle');assert(S.hudTemplates.slots.every(r=>r.slotIndex>=1));const populated=S.hudTemplates.slots.find(r=>r.slotIndex===1);assert.equal(populated.root.type,'image');assert.equal(populated.root['ë'].Ä,-10);}
  if(slotRebuild){const old=S.hudTemplates.slots.find(r=>r.slotIndex===2);const replacement=new old.root.constructor(wrapper('/buildart/inv5.png'),0,0,100,100);const caption=old.nodes.find(n=>n.type==='text'&&n['ë'].Ä===75);replacement.add(new caption.constructor(caption.text,0,75));const emblem=old.nodes.find(n=>n['À']?.src==='/buildart/ammo1.png');replacement.add(new emblem.constructor(wrapper('/buildart/ammo1.png'),25,-25,30,30));old.holder.remove(old.root);old.holder.add(replacement);await tick(1000);assert(S.hudTemplates.slots.find(r=>r.slotIndex===2).root===replacement);assert(!S.hudWarnNodes.has(old.root));assert(S.hudWarnNodes.has(old.holder));assert(S.hudWarnNodes.get(old.holder).__brioHudRecord.root===replacement);}
  if(selectedSlotLive){
   const holder=rec.holder,background=rec.icon,overlay=S.hudWarnNodes.get(holder);assert.equal(overlay.parent,holder);
   const box=()=>{ctxCalls.length=0;S.hudWarnNodes.get(holder).Eââ(ctx,2);return ctxCalls.find(c=>c[0]==='warningRect');};
   background['ë'].Ä=0;const normal=box();background['ë'].Ä=-10;const raised=box();assert.equal(raised[2],normal[2]-5,'live selected lift follows exact native background');background['ë'].Ä=0;assert.deepEqual(box(),normal);
   // Native replaces arrays but leaves old parent pointers; stale root must never define the next border.
   const current=new S.hudSlotSprite.constructor(wrapper('/buildart/inv5.png'),5,-12,110,110);holder['âè']=arr();holder.add(current);assert.equal(background.parent,holder);holder.add(overlay);
   const updated=box();assert.equal(updated[1],(5-55-3)/2);assert.equal(updated[2],(-12-55-3)/2);assert.equal(updated[3],116/2);holder.remove(current);holder.remove(overlay);holder.add(background);holder.add(overlay);await tick(600);
  }
  local['Åé']=[{type:'pickaxe'},{type:'gun'}];local['áAæ']=[];
 }
 // Remote numbers independently warn at 29/19 and never at 30/20; missing counts do not warn.
 remote['ÊÃÄ']=[29,30,31,4];remote['åæ']=[19,20,21,undefined,0];
 const renderWarnings=()=>{ctxCalls.length=0;S.invNodes.get(remote).Eââ(ctx,1);return ctxCalls.filter(x=>x[0]==='fill')};
 await tick(100);let values=renderWarnings();
 // Clock chosen so flash is in its red phase; geometry/rows bind remote values.
 while(Math.sin(clock/140)<0)await tick(50);
 values=renderWarnings();assert(values.some(x=>x[1]==='#ff2020'&&x[2]==='29'));assert(values.some(x=>x[1]==='#ff2020'&&x[2]==='19'));assert(!values.some(x=>x[1]==='#ff2020'&&['30','20','21','31','?'].includes(x[2])));
 let testEffect;
 if(lootEffects){
  const loot={id:950,type:'gun','â':container(),'âê':drawable('/buildart/scar.png'),'ÀÅ':drawable('/buildart/rarity-base.png')};
  testEffect=loot['ÀÅ'];testEffect.opacity=.7;const effectDescriptor=Object.getOwnPropertyDescriptor(testEffect,'opacity');loot['â'].add(loot['âê']);loot['â'].âá(testEffect);stage.add(loot['â']);
  let effectDraws=0;testEffect.éa=function(){if(this.opacity<=0||this.visible===false)return;effectDraws++;for(const n of this['âè'])n.éa?.();};
  players.push(loot);await tick(2500);assert.equal(testEffect.opacity,0);assert.equal(loot['âê'].opacity,1);assert.equal(loot['â'].opacity,1);
  testEffect.add(Object.assign(container(),{type:'particle',éa(){effectDraws++;}}));testEffect.opacity=.85;testEffect.éa();assert.equal(effectDraws,0,'new rarity particles are behind the effect gate');
  tab('Challenges');const toggle=extras.querySelector('[data-extra-id=lootInvisible] input[type=checkbox]');
  toggle.click();assert.equal(testEffect.opacity,.85);testEffect.éa();assert.equal(effectDraws,2);toggle.click();assert.equal(testEffect.opacity,0);
  assert(S.log.some(l=>l.includes('LOOT EFFECT BRANCH')));assert.equal(effectDescriptor.enumerable,Object.getOwnPropertyDescriptor(testEffect,'opacity').enumerable);
 }
 const originalBody=wrapper('/body-update.png');local['Ëå']['À']=originalBody;assert.equal(local['Ëå']['À'].src,'/cosmetics/body/shootem.png');assert.equal(local['head']['À'].src,failHead?'/native-head.png':'/cosmetics/head/shootem.png');assert.equal(local['ÉãÂ'].src,'/cosmetics/pickaxe/trophy.png');local['ä']['À']=wrapper('/gun.png');local['ÈÆ']=1;assert.equal(local['ä']['À'].src,'/gun.png');local['ÈÆ']=0;assert.equal(local['ä']['À'].src,'/cosmetics/pickaxe/trophy.png');local['åëÅ']=10;assert.equal(local['Ëé'],'trail91-');assert.equal(local['ÆÃÅ'],'sunray');local['äÀÊ']=wrapper('/reset-glider.png');assert.equal(local['äÀÊ'].src,'/cosmetics/glider/glider.png');
 for(let i=0;i<4;i++){local['ÄÊâ']['À']=wrapper('/cosmetics/emotes/emote'+(10+i)+'.png');assert.equal(local['ÄÊâ']['À'].src,'/cosmetics/emotes/emote'+(mode==='random'?90:90+i)+'.png');const im=new w.Image;im.src='/buildart/emote'+i+'.png';assert.equal(im.src,'/cosmetics/emotes/emote'+(mode==='random'?90:90+i)+'.png')}
 // Delayed parent availability must remain retryable, followed by native retention/restoration.
 await tick(12000);assert.equal(w.Array.prototype.forEach,nativeForEach);
 const marker={icon:drawable('/buildart/ping-meteor-icon.png'),opacity:1,'ë':{É:500,Ä:20},'èÆÂ':999999,'ÊÈA'(){this.destroyed=true}};players.push(marker);await flush();assert(!marker.parent);stage.add(marker);await flush();if(saturatedDiscovery)await tick(1200);assert(S.log.some(x=>x.includes('METEOR NATIVE HOLD INSTALLED')));stage.remove(marker);assert(stage['âè'].includes(marker));marker.opacity=0;assert.equal(marker.opacity,1);marker['ÊÈA']();assert(!marker.destroyed);
 // Native direct meteor sprite also persists through flag/opacity/removal expiry.
 const mini=Object.assign(drawable('/buildart/ping-meteor.png'),{éa(){}});mini['Äã']=false;const miniParent=detachedHud?hiddenMap:stage;miniParent.add(mini);await flush();if(saturatedDiscovery)await tick(1200);mini['Äã']=true;mini.opacity=0;assert.equal(mini['Äã'],false);assert.equal(mini.opacity,1);miniParent.remove(mini);assert(miniParent['âè'].includes(mini));
 assert.equal(remote.AÃå.height,remote['æÄ'].height);remote.AÃå.height=3;assert.equal(remote.AÃå.height,10);
 for(const k of['æÄ','AÃå']){const n=remote[k]['âè'].find(n=>n.type==='brioFeature');assert(n);n.Eââ(ctx);assert(ctxCalls.some(c=>c[0]==='stroke'&&c[1]==='#fff'&&c[2]===2));assert(ctxCalls.some(c=>c[0]==='fill'&&c[1]==='#000'));n.Eââ(ctx,2);assert(ctxCalls.some(c=>c[0]==='rect'&&c[3]===29&&c[4]===4));const count=ctxCalls.length;remote[k].width=0;n.Eââ(ctx);assert.equal(ctxCalls.length,count);remote[k].width=60}
 const chest={id:3,type:'chest','â':container()},drop={id:4,type:'object','Àâ':'airdrop','â':container()};chest['â']['ë']={É:2500,Ä:2000};drop['â']['ë']={É:-3000,Ä:1000};players.push(chest,drop);S.localTrack.node.Eââ(ctx);await tick(500);assert.equal(S.chestUi.style.display,'block');assert.equal(S.airdropUi.style.display,'block');assert.equal(S.chestUi.querySelector('.shape').style.background,'rgb(255, 210, 28)');assert.equal(S.airdropUi.querySelector('.shape').style.background,'rgb(242, 139, 22)');
 // Local transform -> all arrow quadrants. Net label angle stays within +/-90 degrees.
 for(let deg=-180;deg<=180;deg+=15){remote['â']['ë']={É:5000*Math.cos(deg*Math.PI/180),Ä:5000*Math.sin(deg*Math.PI/180)};S.localTrack.node.Eââ(ctx);await tick(250);const u=S.nearestUi;assert.equal(u.style.display,'block');const a=+u.style.transform.match(/rotate\(([-.\d]+)deg\)/)[1],flip=u.querySelector('.d').style.transform.includes('180')?180:0,net=((a+flip+540)%360)-180;assert(Math.abs(net)<=90.001);assert.match(u.querySelector('.d>span').textContent,/m$/);if(nearestName){assert.equal(u.querySelector('.playerName').textContent,'other');assert.equal(u.querySelector('.playerName').style.fontSize,'16px');assert.equal(u.querySelector('.d').style.height,'38px');assert(!u.querySelector('script'))};assert.match(u.querySelector('.d').getAttribute('style'),/text-stroke/)}
 remote['â']['ë']={É:10,Ä:0};S.localTrack.node.Eââ(ctx);await tick(250);assert.equal(S.nearestUi.style.display,'none');players.splice(players.indexOf(remote),1);await tick(1000);assert.equal(S.nearestUi.style.display,'none');
 assert(!w.document.querySelector('[data-a="phase"]'));local['ÀËá']=20;local['âëä']=200;await tick(500);assert.equal(S.botPhase,'match');assert(S.log.some(x=>x.includes('BOT PHASE')&&x.includes('automatic')));w.document.querySelector('[data-a="copy"]').click();await flush();assert.match(w.copied,/BRIO 52/);
 if(matchLifecycle){
  if(thresholds){for(const [kind,i,v]of [['health',0,42],['ammo',5,8],['materials',3,4]]){const n=extras.querySelector('[data-warning-kind="'+kind+'"][data-warning-index="'+i+'"]');n.value=v;n.dispatchEvent(new w.Event('input'));}}
  const preservedThresholds=JSON.parse(w.localStorage.getItem('brio_extras_state')).warningThresholds;
  const stale=player(30,'stale',9000);players.push(stale);await flush();const epoch=S.runEpoch;w.document.querySelector('#ready').click();await flush();
  assert.equal(S.runEpoch,epoch+1);assert.deepEqual(JSON.parse(w.localStorage.getItem('brio_extras_state')).warningThresholds,preservedThresholds);if(thresholds){const settings=S.log.filter(l=>l.includes('TEST SETTINGS AT PLAY')).at(-1);assert.deepEqual(JSON.parse(settings.slice(settings.indexOf('{'))).allSelected.warningThresholds,preservedThresholds);}if(monochrome){assert(w.document.documentElement.hasAttribute('data-brio-mono-page'));assert.equal(ctx.canvas.style.filter,'contrast(1.2) grayscale(1)');}assert(!stage['âè'].includes(marker));assert(!miniParent['âè'].includes(mini));assert.equal(S.renderer,null);assert.equal(S.remoteRefs.size,0);assert.equal(S.invNodes.size,0);assert.equal(S.trackNodes.size,0);assert.equal(S.nearestUi.style.display,'none');assert.equal(w.localStorage.getItem('br_local_visuals'),JSON.stringify(visuals));
  players.splice(0);const newPlayers=arr(),newLocal=player(1,w.document.querySelector('#nameBox').value,0);newPlayers.push(newLocal);await tick(4000);assert.equal(S.renderer,newLocal);assert.equal(S.remoteRefs.size,0);assert(!S.invNodes.has(stale));
  const newMarker=Object.assign(drawable('/buildart/ping-meteor.png'),{éa(){},'Äã':false});stage.add(newMarker);await flush();await tick(1500);stage.remove(newMarker);assert(stage['âè'].includes(newMarker));
  assert(!stage['âè'].includes(marker));assert(!miniParent['âè'].includes(mini));assert(S.log.filter(l=>l.includes('MATCH STATE RESET')).length===2);
 }
 S.destroy();await tick(4000);if(testEffect)assert.equal(testEffect.opacity,.85);assert(!w.__brio_unlocker_v52);if(monochrome){assert.equal(ctx.canvas.style.filter,'contrast(1.2)');assert(!w.document.documentElement.hasAttribute('data-brio-mono-page'));}if(decoderProbe)assert.equal(w.msgpack.decode,originalDecode);if(engineProbe)assert.equal(w.testEngine['ÁÂ'].player['èæå'],originalCreate);assert.equal(local['Ëå']['À'],originalBody);assert.equal(roof['À']['ÁÄ'],nativeRoof);assert.equal(marker.opacity,0);assert.equal(mini['Äã'],true);assert.equal(mini.opacity,0);assert.equal(remote.AÃå.height,3);assert.equal(w.Array.prototype.forEach,nativeForEach);if(detachedHud){assert(!Object.hasOwn(hiddenHud['âè'],'forEach'));assert(!Object.hasOwn(hiddenMap['âè'],'forEach'));}stage.remove(marker);assert(!stage['âè'].includes(marker));assert.equal(w.document.querySelector('#loggedInLocker').textContent,'Locker');assert.equal(w.localStorage.getItem('br_local_visuals'),JSON.stringify(visuals));
 w.eval(code);await flush();assert(w.__brio_unlocker_v52);w.__brio_unlocker_v52.destroy();assert.deepEqual([...S.errors],[]);dom.window.close();
 return{own,failHead,nativeHud,sixSlotHud,matchLifecycle,probeBudget,result:'passed'};
}
(async()=>{for(const opts of[{own:true},{own:false},{own:true,failHead:true},{mode:'native'},{mode:'invisible'},{mode:'random'},{mode:'custom'},{nativeHud:true},{nativeHud:true,detachedHud:true,plainHud:true},{nativeHud:true,detachedHud:true,plainHud:true,emptyHud:true},{nativeHud:true,detachedHud:true,particleHud:true},{nativeHud:true,detachedHud:true,saturatedDiscovery:true},{decoderProbe:true},{engineProbe:true},{nearestName:true},{nativeHud:true,hudRebuild:true},{nativeHud:true,stackHud:true,ammoDecoration:true},{nativeHud:true,stackHud:true,ammoDecoration:true,fullEngine:true},{nativeHud:true,stackHud:true,sixSlotHud:true},{matchLifecycle:true},{nativeHud:true,detachedHud:true,sixSlotHud:true,matchLifecycle:true},{decoderProbe:true,probeBudget:true},{nativeHud:true,sixSlotHud:true,slotRebuild:true},{nativeHud:true,sixSlotHud:true,inventoryGeometry:true},{monochrome:true,matchLifecycle:true},{thresholds:true},{thresholds:true,nativeHud:true,stackHud:true,sixSlotHud:true,slotCounts:true},{thresholds:true,corrupt:true,nativeHud:true,stackHud:true,sixSlotHud:true},{thresholds:true,fullEngine:true,nativeHud:true,stackHud:true,sixSlotHud:true,slotCounts:true,matchLifecycle:true},{nativeHud:true,sixSlotHud:true,selectedSlotLive:true},{lootEffects:true},{own:false,lootEffects:true}])console.log(await run(opts))})().catch(e=>{console.error(e);process.exitCode=1});
